#!/bin/bash
#By: isca0 igorsca(at)gmail.com
#14/09/15 - Ctba/PR
#
#	Atrelado ao Pograma admenu para Gestao do Firewall (iptables)
#
#
#
#####---Variaveis Globais---#####

#Colors
green="\033[32;40;1m"
red="\033[31;40;1m"
yellow="\033[33;40;1m"
limpa="\033[0m"

#Global var's
SOURCE="/usr/local/bin"
#FIR=$(/etc/rc.d/rc.fir)

#Functions
cad_word(){
if [ -e "$SOURCE"/libs/blacklist ]
then
	if fgrep "$word" "$SOURCE"/libs/blacklist > /dev/null
	then
		echo -e "$red""A palavra "$yellow""$word""$red" ja esta cadastrada!"
	else
		echo "$word" >> "$SOURCE"/libs/blacklist
		echo -e "$green""$word""$limpa"" cadastrada com sucesso!"
		#iptables -A INPUT -m string --algo bm --string "$word" -j DROP
		#iptables -A FORWARD -m string --algo bm --string "$word" -j DROP
	fi
else
		echo "$word" >> "$SOURCE"/libs/blacklist
		echo -e "$green""$word""$limpa"" cadastrada com sucesso!"
		#iptables -A INPUT -m string --algo bm --string "$word" -j DROP
		#iptables -A FORWARD -m string --algo bm --string "$word" -j DROP
fi
	
}

del_word(){
if [ -e "$SOURCE"/libs/blacklist ]
then
	if fgrep "$word" "$SOURCE"/libs/blacklist > /dev/null
	then
		fgrep -v "$word" "$SOURCE"/libs/blacklist > /tmp/words
		mv -f /tmp/words "$SOURCE"/libs/blacklist
		echo -e "$green""$word""$limpa"" removida com sucesso!"
		#iptables -D INPUT -m string --algo bm --string "$word" -j DROP
		#iptables -D FORWARD -m string --algo bm --string "$word" -j DROP
	else
		echo -e "$red""A palavra "$yellow""$word""$red" ainda nao esta cadastrada"
	fi
else
	echo -e "$yellow""Nao existem palavras a serem removidas!""$limpa"
	sleep 1
	
fi
	
}

cad_ip(){
if [ -e "$SOURCE"/libs/allow ]
then
	if fgrep "$ip" "$SOURCE"/libs/allow > /dev/null
	then
		echo -e "$red""O endereco ip "$yellow""$ip""$red" ja esta cadastrado!"
	else
		echo "$ip" >> "$SOURCE"/libs/allow
		echo -e "$green""$ip""$limpa"" cadastrado com sucesso!"
	fi
else
		echo "$ip" >> "$SOURCE"/libs/allow
		echo -e "$green""$ip""$limpa"" cadastrado com sucesso!"
fi
	
}

del_ip(){
if [ -e "$SOURCE"/libs/allow ]
then
	if fgrep "$ip" "$SOURCE"/libs/allow > /dev/null
	then
		fgrep -v "$ip" "$SOURCE"/libs/allow > /tmp/ips
		mv -f /tmp/ips "$SOURCE"/libs/allow
		echo -e "$green""$ip""$limpa"" removido com sucesso!"
	else
		echo -e "$red""O ip "$yellow""$ip""$red" ainda nao esta cadastrado"
	fi
else
	echo -e "$yellow""Nao existem ips a serem removidos!""$limpa"
	sleep 1
	
fi
	
}
case "$1" in
add)
read -p "Qual palavra voce quer bloquear? " word
cad_word

;;
remove)
read -p "Qual palavra voce deseja remover? " word
del_word

;;

lock)
if [ -s "$SOURCE/libs/allow" ]
then 
	for a in `cat "$SOURCE"/libs/allow`
	do
		for i in `cat "$SOURCE"/libs/blacklist`
		do
			
			echo "ALERTA SSL 443 --> Liberacao de $i para $a"	
			iptables -I INPUT -s "$a" -m string --algo bm --string "$i" -p tcp --dport 443 -j ACCEPT
			iptables -I FORWARD -s "$a" -m string --algo bm --string "$i" -p tcp --dport 443 -j ACCEPT
		done
	done
fi
for i in `cat "$SOURCE"/libs/blacklist`
do
	echo "ALERTA SSL 443 --> Droping $i"	
	iptables -A INPUT -m string --algo bm --string "$i" -p tcp --dport 443 -j DROP
	iptables -A FORWARD -m string --algo bm --string "$i" -p tcp --dport 443 -j DROP
done
;;
#for i in `cat "$SOURCE"/libs/blacklist`
#do
#	iptables -A INPUT -m string --algo bm --string "$i" -j DROP
#	iptables -A FORWARD -m string --algo bm --string "$i" -j DROP
#done
#;;

addip)
read -p "Qual ip voce quer liberar? " ip
cad_ip

;;

removeip)
read -p "Qual ip voce deseja remover? " ip
del_ip

;;

clean)
echo -e "$green""Limpando Regras do firewall...""$limpa"
iptables -X
iptables -F
echo -e "$yellow""Firewall desabilitado""$limpa"
;;
list)
cat "$SOURCE"/libs/blacklist|less
;;
listip)
cat "$SOURCE"/libs/allow|less
;;

reset)
sudo /etc/rc.d/rc.fir
;;

menu)
while true
do
	clear
	echo -e "$green""
			 ####################################
			 # (1) Bloquear palavras            #
			 # (2) Desbloquear palavras         #
                         # (3) Listar palavras cadastradas  #
                         # (4) Liberar endereco IP	    #
                         # (5) Remover endereco IP 	    #
                         # (6) Listar enderecos	IP 	    #
                         # (7) Aplicar Regras		    #
			 # (x) sair                         #
			 ####################################
""$limpa"
	read -p "Digite sua opcao: " res
if [ "$res" = 0 ]
then
	echo -e "$red""Voce deve escolher uma opcao do menu!""$limpa"
	clear
fi

if [ "$res" = 1 ]
then
	"$0" add
	sleep 1
	clear
fi

if [ "$res" = 2 ]
then
	"$0" remove
	sleep 1
	clear
fi

if [ "$res" = 3 ]
then
	"$0" list
	clear
fi

if [ "$res" = 4 ]
then
	"$0" addip
	clear
fi
if [ "$res" = 5 ]
then
	"$0" removeip
	clear
fi

if [ "$res" = 6 ]
then
	"$0" listip
	clear
fi

if [ "$res" = 7 ]
then
		
	"$0" reset
	clear
fi

if [ "$res" = x -o "$res" = X ]
then
	break
fi
 
done
;;
*)
echo -e "$yellow""Use "$0":."$limpa"
		
		"$green"add"$limpa"	Adcionar palavras na lista negra
		"$green"addip"$limpa"	Adcionar ips  na lista branca
		"$green"remove"$limpa"	Remover palavras da lista negra
		"$green"removeip"$limpa"Remover ips da lista branca
		"$green"list"$limpa"	Listar palavras na lista negra
		"$green"listip"$limpa"	Listar ips na lista branca
		"$green"clean"$limpa"	Zerar todas as regras do firewall
		"$green"lock"$limpa"	Refazer todos os bloqueios da lista
		"$green"reset"$limpa"	Roda novamente o script local do firewall
		"$green"menu"$limpa"	Menu interativo para adcionar ou remover palavras

"
;;

esac
exit 0
